version: '3.8'

services:
  conversations-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: conversations-manager
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Add your Twilio credentials here
      # - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      # - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    env_file:
      - ../.env  # Use the parent directory's .env file
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: conversations-manager-network